services:
  - type: web
    name: userbot-ot28
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py & python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PORT
        value: 10000
      - key: COOLDOWN_HOURS
        value: 12
      - key: REPLY_MESSAGE
        value: "Hey! My owner is currently offline right now.\n\nFeel free to leave your message, and they'll reply when they're back online."
